Extend the HPKE API
bcgit/bc-java pull request #1471
Opened 2023-08-15 23:13 UTC by thomdev

Extend the HPKE API to:
 - Support encryption/decryption from byte ranges, in order to avoid copies.
 - Allow the sender to specify their ephemeral key pair, which is necessary to validate OHTTP test vectors.
 - Expose non-labeled extract and expand operations on the HKDF.

2023-08-16 12:02 UTC, normanmaurer commented
Thanks a lot @thomdev for the PR... We would love to have this change so we could eventually create an [OHTTP](https://www.ietf.org/archive/id/draft-ietf-ohai-ohttp-09.html) codec for [netty](https://netty.io).

2023-08-16 15:49 UTC, normanmaurer requested changes

2023-08-16 15:49 UTC, normanmaurer commented on core/src/main/java/org/bouncycastle/crypto/hpke/AEAD.java
> +            throw new IllegalStateException("Invalid offset");
```suggestion
            throw new IndexOutOfBoundsException("Invalid offset");
```

2023-08-16 15:49 UTC, normanmaurer commented on core/src/main/java/org/bouncycastle/crypto/hpke/AEAD.java
> +            throw new IllegalStateException("Invalid length");
```suggestion
            throw new IndexOutOfBoundsException("Invalid length");
```

2023-08-16 15:49 UTC, normanmaurer commented on core/src/main/java/org/bouncycastle/crypto/hpke/AEAD.java
> +            throw new IllegalStateException("Invalid offset");
```suggestion
            throw new IndexOutOfBoundsException("Invalid offset");
```

2023-08-16 15:49 UTC, normanmaurer commented on core/src/main/java/org/bouncycastle/crypto/hpke/AEAD.java
> +            throw new IllegalStateException("Invalid length");
```suggestion
            throw new IndexOutOfBoundsException("Invalid length");
```

2023-08-18 08:17 UTC, dghgit commented
Thanks for the patch. Now merged.

2023-08-18 08:17 UTC, closed without merging