Implement message decryption using SEIPDv2 and PKESKv6 packets
bcgit/bc-java pull request #1768
Opened 2024-08-06 14:30 UTC by vanitasvitae

This PR fixes decryption of messages which make use of version 6 Public-Key-Encrypted-Session-Key packets (PKESKv6) and version 2 Symmetrically-Encrypted-Integrity-Protected-Data packets (SEIPDv2).

Such packets are used for OpenPGP v6 style message encryption using AEAD.

This PR is currently based on #1752.

Debugging the decryption was a bit messy, so expect some more cleanup :)

2024-08-06 14:31 UTC, vanitasvitae commented on pg/src/main/java/org/bouncycastle/openpgp/operator/jcajce/JcaJcePGPUtil.java
> +        return new HybridValueParameterSpec(Arrays.concatenate(ephmeralPublicKey, pkp.getKey().getEncoded()), true, new UserKeyingMaterialSpec(Strings.toByteArray("OpenPGP " + algorithmName)));
Finding this bugger was a pain! :D

2024-08-06 14:55 UTC, vanitasvitae commented
I will try to minimize the diff and then mark this PR as ready.

2024-08-25 23:55 UTC, D4954484 requested changes
#39

2024-09-11 07:51 UTC, merged

2024-09-11 08:59 UTC, vanitasvitae commented
Apparently this was merged and immediatelly reverted? Was that a mistake?

2024-09-13 15:32 UTC, vanitasvitae commented
In main as 58713da3e5f5a84f9aa76fb165f350b73b5fe6e2